name: sync2gitee

on:
  push:
  schedule:
    - cron: '1 17 * * *'

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repos to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:wa143825/taro-template.git'
          destination-repo: 'git@gitee.com:re_vive/taro-template.git'
