name: sync2gitee

on:
  push:
  schedule:
    - cron: '1 17 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/wa143825'
          dst: 'gitee/re_vive'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'taro-template'
          force_update: true
          debug: true
